# Generated by Django 4.2.6 on 2023-10-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
