# Generated by Django 4.2.6 on 2023-10-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCompany', '0002_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
