# Generated by Django 4.2.6 on 2023-10-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCompany', '0003_location_address_location_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name', 'address'], 'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположение'},
        ),
    ]
