# Generated by Django 4.2.6 on 2023-10-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutCompany", "0005_alter_location_address_alter_location_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, verbose_name="Название новости"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("photo", models.FileField(upload_to="", verbose_name="Фотография")),
            ],
            options={
                "verbose_name": "Новостной баннер",
                "verbose_name_plural": "Новостной баннер",
                "ordering": ["title", "description"],
            },
        ),
    ]
