# Generated by Django 4.2.4 on 2023-10-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCompany', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.DateTimeField(verbose_name='Во сколько посетил')),
                ('http_user_agent', models.TextField(verbose_name='HTTP User Agent')),
                ('request_method', models.TextField(verbose_name='Метод запроса')),
            ],
            options={
                'verbose_name': 'Логирование посещений',
                'verbose_name_plural': 'Логирование посещений',
                'ordering': ['viewed'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название новости'),
        ),
    ]
