# Generated by Django 4.2.6 on 2023-10-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyalty',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
