# Generated by Django 4.2.6 on 2023-10-12 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyalty_points_loyalty_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='points',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='stars',
            field=models.SmallIntegerField(),
        ),
    ]
