# Generated by Django 4.2.6 on 2023-10-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_coupons_descriptions_coupons_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
