# Generated by Django 4.2.6 on 2023-10-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_loyalty_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
    ]
