# Generated by Django 4.2.6 on 2023-10-13 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_rename_coupons_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['name', 'discount'], 'verbose_name': 'Скидки и акции', 'verbose_name_plural': 'Скидки и акции'},
        ),
        migrations.AlterModelOptions(
            name='loyalty',
            options={'ordering': ['name', 'points', 'stars'], 'verbose_name': 'Накопительная система', 'verbose_name_plural': 'Накопительная система'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='points',
            field=models.SmallIntegerField(verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='stars',
            field=models.SmallIntegerField(verbose_name='Звездочки'),
        ),
    ]
