# Generated by Django 4.2.6 on 2023-10-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drink_photo_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Категории позиций', 'verbose_name_plural': 'Категории позиций'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['title', 'price', 'cat'], 'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.FileField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.SmallIntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
