# Generated by Django 4.2.6 on 2023-10-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото пользователя'),
        ),
    ]
