# Generated by Django 4.2.6 on 2023-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Посетитель", "verbose_name_plural": "Посетители"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
