# Generated by Django 4.2.6 on 2023-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_visitor_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='surName',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='telephone',
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя посетителя'),
            preserve_default=False,
        ),
    ]
